AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  Game Suggestion API - Flask app deployed to AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Resources:
  SharedLogicLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: game-suggestion-api-shared
      ContentUri: src/app/
      CompatibleRuntimes:
        - python3.12
      Description: Shared code layer for Lambda functions

  SharedDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: game-suggestion-api-dependencies
      ContentUri: dependency-layer/
      CompatibleRuntimes:
        - python3.12
      Description: Shared dependencies layer for Lambda functions

  PlayerApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: player-api
      Handler: lambda_handler.lambda_handler
      CodeUri: src/lambdas/rest/
      Runtime: python3.12
      Description: Player API Lambda Function
      Events:
        GetPlayerByName:
          Type: Api
          Properties:
            Path: /player
            Method: GET
            RestApiId: !Ref PlayerApi
      Layers:
        - !Ref SharedLogicLayer
        - !Ref SharedDependenciesLayer
      Environment:
        Variables:
          TINYDB_BUCKET: !Ref TinyDBBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TinyDBBucket

  PlayerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PlayerApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  TinyDBBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-tinydb-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${PlayerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
