version = 0.1

[default.deploy.parameters]
stack_name = "game-suggestion-api"
resolve_s3 = true
s3_prefix = "game-suggestion-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides="StageName=prod"
