AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Game Suggestion API - Flask app deployed to AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Resources:
  GameSuggestionApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: game-suggestion-api
      Handler: lambda_handler.handler
      CodeUri: .
      Runtime: python3.12
      Description: Game Suggestion API Lambda Function
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          FLASK_ENV: production

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"