AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  Game Suggestion API - AWS app to manage players, games, and create game suggestions.

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12

Parameters:
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment stage (dev or prod)

Resources:
  SharedLogicLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "game-suggestion-api-shared-layer-${StageName}"
      ContentUri: shared-logic-layer/
      CompatibleRuntimes:
        - python3.12
      Description: Shared logic layer for Lambda functions

  SharedDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "game-suggestion-api-dependencies-layer-${StageName}"
      ContentUri: dependency-layer/
      CompatibleRuntimes:
        - python3.12
      Description: Shared dependencies layer for Lambda functions

  RestApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "game-suggestion-api-rest-function-${StageName}"
      Handler: lambda_handler.lambda_handler
      CodeUri: lambdas/rest/
      Runtime: python3.12
      Description: Game Suggestion API Lambda Function
      Events:
        GetPlayerByName:
          Type: Api
          Properties:
            Path: /player
            Method: GET
            RestApiId: !Ref RestApi
        AddPlayer:
          Type: Api
          Properties:
            Path: /player
            Method: POST
            RestApiId: !Ref RestApi
      Layers:
        - !Ref SharedLogicLayer
        - !Ref SharedDependenciesLayer
      Environment:
        Variables:
          TINYDB_BUCKET: !Ref TinyDBBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TinyDBBucket

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "game-suggestion-api-rest-api-${StageName}"
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  CommandsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "game-suggestion-api-commands-function-${StageName}"
      Handler: lambda_handler.lambda_handler
      CodeUri: lambdas/commands
      Runtime: python3.12
      Description: Game Suggestion API Lambda Function
      Events:
        RefreshPlayerGames:
          Type: Api
          Properties:
            Path: /refresh
            Method: GET
            RestApiId: !Ref CommandsApi
        SharedGames:
          Type: Api
          Properties:
            Path: /shared
            Method: GET
            RestApiId: !Ref CommandsApi
        SuggestGames:
          Type: Api
          Properties:
            Path: /suggest
            Method: GET
            RestApiId: !Ref CommandsApi
      Layers:
        - !Ref SharedLogicLayer
        - !Ref SharedDependenciesLayer
      Environment:
        Variables:
          TINYDB_BUCKET: !Ref TinyDBBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TinyDBBucket

  CommandsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "game-suggestion-api-commands-api-${StageName}"
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  TinyDBBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-tinydb-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  RestApiUrl:
    Description: "API Gateway endpoint URL for REST API"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"

  CommandsApiUrl:
    Description: "API Gateway endpoint URL for Commands API"
    Value: !Sub "https://${CommandsApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
